
.PHONY : all definitions thesis src

CHPTS_TEX = $(shell for c in `cd thesis; ls chpt_*.tex`; do echo thesis/chapters/$$c; done)
CHPTS = $(subst .tex,.pdf,${CHPTS_TEX})

all: src thesis 

src/Makefile:
	cd src; coq_makefile -I . automata.v base.v glue.v misc.v myhill_nerode.v re_fa.v     regexp.v re_standard.v tactics.v transitive_closure.v  > Makefile

src: src/Makefile
	cd src; make

thesis/chapters/%.pdf: thesis/%.tex
	j=$(shell basename $@ .pdf); cd thesis; pdflatex -jobname=chapters/$$j "\includeonly{$$j,includes.tex}\input{thesis}"

tex_doc: src
	mkdir -p docs/tex
	coqdoc -d docs/tex --latex --body-only src/*.v

html_doc: src
	mkdir -p docs/html
	coqdoc -d docs/html src/*.v

html_doc_beautiful: html_doc
	mv docs/html/index.html docs/html/index.html.old
	docs/undup.sh docs/html/index.html.old docs/html/index.html
	rm docs/html/index.html.old
	python2.6 docs/beautifier.py docs/html/transitive_closure.html > docs/html/transitive_closure.html.tmp
	mv docs/html/transitive_closure.html.tmp docs/html/transitive_closure.html
	python2.6 docs/beautifier.py docs/html/automata.html > docs/html/automata.html.tmp
	mv docs/html/automata.html.tmp docs/html/automata.html
	python2.6 docs/beautifier.py docs/html/misc.html > docs/html/misc.html.tmp
	mv docs/html/misc.html.tmp docs/html/misc.html

docs/definitions: src docs/extract_definitions.py
	mkdir -p docs/definitions
	rm -f docs/definitions/*
	find src -type f -name '*.v' -exec sh -c 'cat "{}" | sed -e "N;s/{\(|\?\)\s*\n\s*/{\1 /;P;D" | sed -e "N;s/\n\s*\(|\?\)}\s*/ \1}/;P;D" |  python docs/extract_definitions.py `basename "{}" .v` docs/definitions' \; 

definitions: docs/definitions

thesis/chapters:
	mkdir thesis/chapters

thesis/thesis.pdf: definitions thesis/*.tex thesis/vc.tex thesis/chapters ${CHPTS}
	cd thesis; latexmk -pdf thesis

thesis: thesis/thesis.pdf

thesis/code.pdf: tex_doc
	echo -n > thesis/code_all.tex
	FILES=`cd src; make --dry-run -B 2>&1 | grep coqc | awk -F' ' '{print $$5".tex"}' `; for f in $$FILES; do cat docs/tex/$$f >> thesis/code_all.tex; done
	cd thesis; latexmk -pdf code

doc: definitions html_doc tex_doc

clean:
	rm -rf docs/html/* docs/definitions/*


thesis/vc.tex: .git/logs/HEAD
	( \
	echo "%%% This file is generated by Makefile."; \
	echo "%%% Do not edit this file!\n%%%"; \
	git log -1 --format="format:\
	\\gdef\\GITAbrHash{%h}\
	\\gdef\\GITAuthorDate{%ad}\
	\\gdef\\GITAuthorName{%an}%%"; \
	) > thesis/vc.tex
