
presentation.pdf: presentation.tex bib.bib
	latexmk -f -pdf presentation.tex
	
clean:
	latexmk -c presentation.tex

#presentation.pdf: presentation.rst *.style
#	rst2pdf -s presentation.style,a4-landscape,twelvepoint,freetype-sans,bullets.style,text.style presentation.rst 
